//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags_photo
    {
        public int Id { get; set; }
        public string Zone { get; set; }
        public string Person { get; set; }
        public string Event { get; set; }
        public string Automobile { get; set; }
        public string Other_tags { get; set; }
        public int Photo_Id { get; set; }
    
        public virtual Photos Photo { get; set; }
    }
}
