//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Medias> Medias { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Tags_video> Tags_video { get; set; }
        public virtual DbSet<Tags_photo> Tags_photo { get; set; }
    }
}
